name: al_khaliq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  in_app_review: ^2.0.9
  package_info_plus: ^8.1.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.2
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  flutter_background: ^1.2.0
  webview_flutter: ^4.8.0
  in_app_purchase: ^3.1.13
  http: ^1.1.0
  supabase_flutter: ^2.5.0

  

  # Audio
  just_audio: ^0.10.4 
  audio_service: ^0.18.10 
  audio_session: ^0.2.2 
  path_provider: ^2.1.2 
  

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.0
  purchases_flutter: ^9.9.0
  purchases_ui_flutter: ^9.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  dart_jsonwebtoken: ^2.14.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/assetImages/
    - assets/images/icons/
    - shorebird.yaml

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/alKhaliqLogo.png"

fonts:
  - family: Excon
    fonts:
      - asset: assets/fonts/Excon-Black.ttf
        weight: 900
      - asset: assets/fonts/Excon-Bold.ttf
        weight: 700
      - asset: assets/fonts/Excon-Medium.ttf
        weight: 600
      - asset: assets/fonts/Excon-Regular.ttf
        weight: 500
      - asset: assets/fonts/Excon-Light.ttf
        weight: 400
      - asset: assets/fonts/Excon-Thin.ttf
        weight: 300
